"""COLUMN HEADINGS"""
STATEID = 0
VOTERID = 1
PRECINCT = 2
AGE = 3
GENDER = 4 #F/M
PERM_VBM = 5 #can be NaN
SCORE = 6
DVOTE = 7
RVOTE = 8
VOTED = 9
LITBAG = 11
ENVELOPE = 12
POSTCARD = 13
TEXT = 14